#!/bin/bash
#
# Note: on macports this requires librsvg.
#
# For current guidelines, see:
# https://developer.apple.com/design/human-interface-guidelines/toolbars
#
# Currently (late 2023): 24pt for iOS/iPadOS, 19pt for macOS, or
# 32pt for macOS full-colour free-standing icon.
#
# Line widths have been chosen to visually match what SFSymbols produces for
# system images (late 2023):
#
#   - 512x512 canvas -> 28pt
#   - 640x640 canvas -> 35pt
#
set -e

function render {
    src=$1
    size=$2
    filename=$3

    if [ "$size" = 19 -a -e "$src-lores.svg" ]; then
      echo "$filename: using lo-res SVG"
      rsvg-convert -w$size -h$size $src-lores.svg -o $filename
    elif [ -e "$src-$size.svg" ]; then
      echo "$filename: using ${size}x SVG"
      rsvg-convert -w$size -h$size $src-$size.svg -o $filename
    else
      rsvg-convert -w$size -h$size $src.svg -o $filename
    fi
}

for i in "$@"; do
  for j in 19 24; do
    render $i $j $i-$j.png
    render $i $(($j+$j)) $i-$j@2x.png
    render $i $(($j+$j+$j)) $i-$j@3x.png
  done
done
