#!/bin/bash
set -e

me="`whoami`"
if [ "$me" = root ]; then
  echo "This script should be run as the build user."
  exit 1
fi

version="$1"
if [ -z "$1" ]; then
  echo "Example usage: $0 7.3.1"
  exit 1
fi

distro=`(. /etc/os-release; echo "$VERSION_ID")`
if [ -z "$distro" ]; then
  echo "I could not determine the fedora/opensuse release version."
  exit 1
fi

flavour=`(. /etc/os-release; echo "$NAME")`
if [ -z "$flavour" ]; then
  echo "I could not determine the flavour of GNU/Linux distribution."
  exit 1
fi
case "$flavour" in
  Fedora*)
    flavour=Fedora
    specbase=regina-fedora
    ;;
  openSUSE*)
    flavour=openSUSE
    specbase=regina-suse
    ;;
  *)
    echo "I could not determine the flavour of GNU/Linux distribution."
    echo "I am trying to interpret: $flavour"
    exit 1
    ;;
esac

if [ -e "/src/pkg/$specbase-$distro.spec" ]; then
  spec="$specbase-$distro.spec"
elif [ -e "/src/pkg/$specbase.spec" ]; then
  spec="$specbase.spec"
else
  echo "ERROR: Cannot find spec file."
  exit 1
fi

echo "Building regina-$version for $flavour $distro using $spec... ok?"
read

export RPM_BUILD_NCPUS=16

cd ~
if [ -e .rpmmacros ]; then
  echo 'ERROR: Pre-existing .rpmmacros:'
  cat .rpmmacros
  exit 1
fi
echo '%vendor Regina' > .rpmmacros

patches=
case "$flavour" in
  Fedora)
    patches=`cat /src/pkg/"$spec" | grep '^\S*\.diff$'` || true
    ;;
  openSUSE)
    patches=`cat /src/pkg/"$spec" | grep ^Patch | cut -f2 -d' '` || true
    ;;
  *)
    # Should never occur
    echo "Unknown flavour of GNU/Linux distribution: $flavour"
    exit 1
    ;;
esac

cd rpmbuild
cp /src/pkg/regina-"$version".tar.gz SOURCES
if [ -n "$patches" ]; then
  for i in $patches; do cp /src/pkg/"$i" SOURCES; done
fi
cp /src/pkg/"$spec" SPECS
cd SPECS
rpmbuild -ba "$spec"
cd ..
echo
echo 'Happy to purge source & build directories?'
read

rm -rf BUILDROOT BUILD SPECS SOURCES

echo
echo 'BEFORE quitting, from the host machine, run:'
echo "  docker cp VM_NAME:/home/build/rpmbuild /data/regina/bin/$distro"
echo

exit 0
