#!/bin/bash
set -e

me="`whoami`"
if [ "$me" = root ]; then
  echo "This script should be run as the build user."
  exit 1
fi

version="$1"
if [ -z "$1" ]; then
  echo "Example usage: $0 7.3.1"
  exit 1
fi

distro=sid

echo "Building SOURCE-ONLY regina-$version for $distro... ok?"
read

cd ~
mkdir debian
cd debian
cp /src/pkg/regina-"$version".tar.gz regina-normal_"$version".orig.tar.gz
tar -zxf regina-normal_"$version".orig.tar.gz
mv regina-"$version" regina-normal-"$version"
cd regina-normal-"$version"

tar -zxf /src/pkg/"$distro".tgz
debuild -S || true

echo
echo "Purging builddir..."
cd ..
rm -rf regina-normal-"$version"
echo
echo 'BEFORE quitting, from the host machine, run:'
echo "  docker cp VM_NAME:/home/build/debian /data/regina/bin/${distro}_src"
echo

exit 0
