#!/bin/bash
set -e

me="`whoami`"
if [ "$me" = root ]; then
  echo "This script should be run as the build user."
  exit 1
fi

version="$1"
if [ -z "$1" ]; then
  echo "Example usage: $0 7.3.1"
  exit 1
fi

if [ ! -e /src/pkg/PKGBUILD ]; then
  echo 'ERROR: Cannot locate PKGBUILD.'
  exit 1
fi

echo "Building regina-$version for arch... ok?"
read

patches=`cat /src/pkg/PKGBUILD | grep '^\s*patch .*\.diff"' | sed -e 's#.*/##' | sed -e 's#\"##'`

export MAKEFLAGS='-j16'

cd ~
mkdir arch
cp /src/pkg/PKGBUILD /src/pkg/regina-"$version".tar.gz arch
for i in $patches; do cp /src/pkg/"$i" arch; done
cd arch
makepkg
echo
echo 'Happy to continue?'
read
namcap PKGBUILD
namcap regina-normal-"$version"-*.zst
echo
echo 'Happy to purge source & build directories?'
read

rm -rf pkg src
rm -f PKGBUILD regina-"$version".tar.gz
for i in $patches; do rm -f $i; done
rm -rf regina-normal-debug-*.zst

echo
echo 'BEFORE quitting, from the host machine, run:'
echo "  docker cp VM_NAME:/home/build/arch /data/regina/bin/arch"
echo

exit 0
