#!/bin/bash
set -e

# Usage: render source.svg dest.png size
function render {
  rsvg-convert -w$3 -h$3 "$1" -o "$2"
}

# render front-reverse-opaque.svg front.png 1024
# render back.svg back.png 1024

render front-coloured.svg front.png 1024
render back-coloured.svg back.png 1024

