#!/usr/bin/env bash
set -e

ver="$1"
if [ ! -e "/usr/share/debootstrap/scripts/$ver" ]; then
  echo "Unsupported Debian version: $ver"; exit 1
fi

# Support history for architectures in debian:
# - amd64: only supported for >= etch (debian 4)
# - arm64: only supported for >= jessie (debian 8)
# - i386:  supported for all versions

myarch="`uname -m`"

arch="$2"
if [ -n "$arch" ]; then
  case "$arch" in
    i386) ;;
    amd64) echo "Cannot explicitly request architecture: $arch"; exit 1;;
    arm64) echo "Cannot explicitly request architecture: $arch"; exit 1;;
    *) echo "Unsupported Debian architecture: $arch"; exit 1;;
  esac
fi

if [ -n "$arch" ]; then
  tag="bare/debian:${ver}_${arch}"
else
  tag="bare/debian:$ver"
  arch=`dpkg --print-architecture`
fi

# Ancient debian versions live on the archive mirror and/or use old signing
# keys, but debootstrap is not aware of this.
# The ones we care about are listed below.
#
# Note: modern amd64 kernels are incompatible with glibc < 2.14 (see
# debian #875981), which means that any debian earlier than jessie needs to be
# i386 only.
#
# Warning: woody appears to build successfully, but there are visible issues.
# For example: debootstrap fails to mount /sys; also, when fine-tuning the APT
# configuration, dpkg warns about "architecture `i386-none' not in remapping
# table".  These issues might well come back to bite us.

archive=0
case "$ver" in
  # These are the ancient debian versions that we do not yet support.
  # We keep them here anyway, going all the way back to the date of the first
  # public release of regina, in case we ever want to try:
  potato ) archive=1 ; oldkey=1 ;;
  # These are the ancient debian versions that we do support:
  woody ) archive=1 ; oldkey=1 ;;
  sarge ) archive=1 ; oldkey=1 ;;
  etch ) archive=1 ; oldkey=1 ;;
  lenny ) archive=1 ; oldkey=1 ;;
  squeeze ) archive=1 ; oldkey=1 ;;
  wheezy ) archive=1 ; oldkey=1 ;;
  jessie ) archive=1 ; oldkey=1 ;;
  stretch ) archive=1 ;;
  * ) ;;
esac

debootstrap_opts="--arch=$arch"
debootstrap_args="$ver"

if [ "$archive" = 1 ]; then
  debootstrap_args="$debootstrap_args http://archive.debian.org/debian"
fi
if [ "$oldkey" = 1 ]; then
  debootstrap_opts="$debootstrap_opts --keyring=/usr/share/keyrings/debian-archive-removed-keys.gpg"
fi

# Some extra packages that we need to support apt-check-sigs:
if [ "$ver" = sarge ]; then
  # Add gnupg and its dependencies.
  debootstrap_opts="$debootstrap_opts --include=gnupg,libbz2-1.0,libldap2,libreadline5,libsasl2,libusb-0.1-4"
elif [ "$ver" = woody ]; then
  # Add gnupg and its dependencies, as well as wget (which has no dependencies
  # that we do not already have).
  debootstrap_opts="$debootstrap_opts --include=wget,gnupg,libgdbmg1,zlib1g"
fi

echo "Preparing Debian $ver ($arch) as $tag ..."
echo
./mkimage.sh -t "$tag" debootstrap $debootstrap_opts $debootstrap_args

exit 0
