#!/usr/bin/env bash
set -e

ver="$1"
if [ ! -e "/usr/share/debootstrap/scripts/$ver" ]; then
  echo "Unsupported Debian version: $ver"; exit 1
fi

myarch="`uname -m`"

arch="$2"
if [ -n "$arch" ]; then
  case "$arch" in
    i386) ;;
    amd64) echo "Cannot explicitly request architecture: $arch"; exit 1;;
    arm64) echo "Cannot explicitly request architecture: $arch"; exit 1;;
    *) echo "Unsupported Debian architecture: $arch"; exit 1;;
  esac
fi

if [ -n "$arch" ]; then
  tag="bare/debian:${ver}_${arch}"
else
  tag="bare/debian:$ver"
  arch=`dpkg --print-architecture`
fi

# Ancient debian versions live on the archive mirror and/or use old signing
# keys, but debootstrap is not aware of this.
# The ones we care about are listed below.
#
# Note: modern kernels are incompatible with glibc < 2.14 (see debian #875981),
# which means we cannot support any debian earlier than jessie.

archive=0
case "$ver" in
  # These are the ancient debian versions that we do not support.
  # We keep them here anyway, going all the way back to the date of the first
  # public release of regina, in case we ever want to try again:
  potato ) archive=1 ; oldkey=1 ;;
  woody ) archive=1 ; oldkey=1 ;;
  sarge ) archive=1 ; oldkey=1 ;;
  etch ) archive=1 ; oldkey=1 ;;
  lenny ) archive=1 ; oldkey=1 ;;
  squeeze ) archive=1 ; oldkey=1 ;;
  wheezy ) archive=1 ; oldkey=1 ;;
  # These are the ancient debian versions that we do support:
  jessie ) archive=1 ; oldkey=1 ;;
  stretch ) archive=1 ;;
  * ) ;;
esac

debootstrap_opts="--arch=$arch"
debootstrap_args="$ver"

if [ "$archive" = 1 ]; then
  debootstrap_args="$debootstrap_args http://archive.debian.org/debian"
fi
if [ "$oldkey" = 1 ]; then
  debootstrap_opts="$debootstrap_opts --keyring=/usr/share/keyrings/debian-archive-removed-keys.gpg"
fi

echo "Preparing Debian $ver ($arch) as $tag ..."
echo
./mkimage.sh -t "$tag" debootstrap $debootstrap_opts $debootstrap_args

exit 0
