#!/usr/bin/env bash
set -e

ver="$1"
if [ ! -e "/usr/share/debootstrap/scripts/$ver" ]; then
  echo "Unsupported Ubuntu version: $ver"; exit 1
fi

# Support history for architectures in ubuntu:
# - amd64: supported for all versions
# - arm64: only supported for >= 13.10 (saucy)
# - i386:  only full supported as a desktop for <= 17.04 (zesty) and in
#          any form for <= 19.04 (disco)

myarch="`uname -m`"

arch="$2"
if [ -n "$arch" ]; then
  case "$arch" in
    i386) ;;
    amd64) echo "Cannot explicitly request architecture: $arch"; exit 1;;
    arm64) echo "Cannot explicitly request architecture: $arch"; exit 1;;
    *) echo "Unsupported Ubuntu architecture: $arch"; exit 1;;
  esac
fi

if [ -n "$arch" ]; then
  tag="bare/ubuntu:${ver}_${arch}"
else
  tag="bare/ubuntu:$ver"
  arch=`dpkg --print-architecture`
fi

# Some ubuntu versions live on the old-releases mirror and/or use old
# signing keys, but debootstrap is not aware of this.
# The ones we care about are listed below.
#
# Note: modern kernels are incompatible with glibc < 2.14 (see debian #875981),
# which means we cannot support any ubuntu earlier than precise.
#
archive=0
oldkey=0
case "$ver" in
  # The very first LTS releases: these are beyond our current reach, but we
  # list them here in case we ever want to attempt them anyway.
  dapper ) oldkey=1 ;; #  6.06 LTS
  hardy ) oldkey=1 ;;  #  8.04 LTS
  lucid ) oldkey=1 ;;  # 10.04 LTS
  # LTS releases:
  precise ) oldkey=1 ;;
  # Interim releases:
  quantal ) archive=1 ;;
  raring ) archive=1 ;;
  saucy ) archive=1 ;;
  utopic ) archive=1 ;;
  vivid ) archive=1 ;;
  wily ) archive=1 ;;
  yakkety ) archive=1 ;;
  zesty ) archive=1 ;;
  artful ) archive=1 ;;
  cosmic ) archive=1 ;;
  disco ) archive=1 ;;
  eoan ) archive=1 ;;
  groovy ) archive=1 ;;
  hirsute ) archive=1 ;;
  impish ) archive=1 ;;
  kinetic ) archive=1 ;;
  * ) ;;
esac

debootstrap_opts="--arch=$arch"
debootstrap_args="$ver"

if [ "$archive" = 1 ]; then
  debootstrap_args="$debootstrap_args http://old-releases.ubuntu.com/ubuntu"
fi
if [ "$oldkey" = 1 ]; then
  debootstrap_opts="$debootstrap_opts --keyring=/usr/share/keyrings/ubuntu-archive-removed-keys.gpg"
fi

echo "Preparing Ubuntu $ver ($arch) as $tag ..."
echo
./mkimage.sh -t "$tag" debootstrap $debootstrap_opts $debootstrap_args

exit 0
