#!/bin/bash
set -e

suite="$1"

mirror=http://mirror.aarnet.edu.au/pub/ubuntu/archive
ports=http://ports.ubuntu.com/ubuntu-ports

arch=`uname -m`
if [ "$arch" = aarch64 ]; then
  echo deb "$ports" "$suite" main universe
  echo deb "$ports" "$suite"-security main universe
else
  echo deb "$mirror" "$suite" main universe
  echo deb "$mirror" "$suite"-security main universe
fi
