#!/bin/bash
#
# Creates a tarball of each type of debian directory for easy transportation.
#
# Usage:
#    mkdirballs [ <dist> ... ]
#
# If no <dist> arguments are given, then all will be generated.
#
set -e

if [ -e debian ]; then
	echo "Please remove the debian directory (or file)."
	exit 1
fi

bundle() {
	if [ ! -e "$1/control" ]; then
		echo "ERROR: $1 does not look like a debian packaging directory."
		return
	fi
	echo "Making $1 ..."
	mkdir debian
	cp -pr $1/* debian
	tar -zcf $1.tgz debian
	rm -rf debian
}

if [ "$#" == 0 ]; then
	for i in *; do
		if [ -d "$i" -a -e "$i/control" ]; then
			bundle "$i"
		fi
	done
else
	for i in "$@"; do
		bundle "$i"
	done
fi
