#!/bin/bash
set -e

# Usage: render source.svg dest.png size
function render {
  rsvg-convert -w$3 -h$3 "$1" -o "$2"
  # inkscape -z -e "$2" -w $3 -h $3 "$1"
}

# OSX icons:
rm -rf regina.iconset x-regina.iconset
mkdir regina.iconset x-regina.iconset
for i in 16 32 128 256 512; do
  size=$i
  render regina.svg regina.iconset/icon_${i}x${i}.png $size
  render x-regina.svg x-regina.iconset/icon_${i}x${i}.png $size
  size=$(($i + $i))
  render regina.svg regina.iconset/icon_${i}x${i}@2x.png $size
  render x-regina.svg x-regina.iconset/icon_${i}x${i}@2x.png $size
done
if [ -x /usr/bin/xcrun ]; then
  xcrun iconutil -c icns regina.iconset
  xcrun iconutil -c icns x-regina.iconset
  rm -rf regina.iconset x-regina.iconset
fi

# MSWindows icons:
rm -f regina.ico x-regina.ico
rm -rf mswindows
mkdir mswindows
sizes="16 24 32 48 64 256"
for i in $sizes; do
  size=$i
  render regina.svg mswindows/regina-${i}.png $size
  render x-regina.svg mswindows/x-regina-${i}.png $size
done
for i in regina x-regina; do
  sources=
  for j in $sizes; do
    sources="$sources mswindows/$i-$j.png"
  done
  convert $sources $i.ico
done
rm -rf mswindows

# XDG icons:
rm -rf xdg
mkdir xdg
for i in 16 22 24 32 48 64 128 256; do
  size=$i
  render regina.svg xdg/regina-${size}.png $size
  render x-regina.svg xdg/x-regina-${size}.png $size
done

# QtUI icons:
rm -rf qtui
mkdir qtui
for i in 16 22 32 48 64; do
  size=$i
  render regina.svg qtui/regina-${i}.png $size
  size=$(($i + $i))
  render regina.svg qtui/regina-${i}@2x.png $size
done

# iOS document icons:
# - ReginaLarge: 310 (x1,2,3)
# - Packets/Document: 32 (x1,2,3)
# - RGA DocType: 64 320
rm -rf ios
mkdir ios
for i in 32 310; do
  size=$i
  render regina.svg ios/regina-${i}.png $size
  size=$(($i+$i))
  render regina.svg ios/regina-${i}@2x.png $size
  size=$(($i+$i+$i))
  render regina.svg ios/regina-${i}@3x.png $size
done
for i in 64 320; do
  size=$i
  render regina.svg ios/regina-doc-${size}.png $size
done

# iOS app icons (reversed):
for i in 40 58 60 76 80 87 114 120 128 136 152 167 180 192 1024; do
  render app.svg ios/app-$i.png $i
  render app-dark.svg ios/app-dark-$i.png $i
  render app-tinted.svg ios/app-tinted-$i.png $i
done

for i in 120; do
  # These sizes are used twice.
  cp -p ios/app-$i.png ios/app-${i}-1.png
  cp -p ios/app-dark-$i.png ios/app-dark-${i}-1.png
  cp -p ios/app-tinted-$i.png ios/app-tinted-${i}-1.png
done

# The same iOS app icons (reversed) but for the macOS build:
rm -rf macos
mkdir macos
for i in 16 32 64 128 256 512 1024; do
  render app.svg macos/app-$i.png $i
done

for i in 32 256 512; do
  # These sizes are used twice.
  cp -p macos/app-$i.png macos/app-${i}-1.png
done

convert -alpha off ios/app-1024.png appstore.png

