#!/bin/bash
set -e

wix_version=3.11

echo "Cleaning old files..."
echo
rm -fv Regina.wxs *.wixobj *.wixpdb *.msi

echo

arch=`uname -m`
if [ "$arch" = 'x86_64' ]; then
  wix_arch=x64
  wix_dir="/c/Program Files (x86)/WiX Toolset v$wix_version"
elif [ "$arch" = 'i686' ]; then
  wix_arch=x86
  wix_dir="/c/Program Files/WiX Toolset v$wix_version"
else
  echo "ERROR: Unknown architecture: $arch"
  exit 1
fi

if [ ! -e ./mkwxs.pl ]; then
  echo 'ERROR: Missing mkwxs.pl'
  exit 1
fi

if [ ! -d "$wix_dir" ]; then
  echo "ERROR: Missing Wix: $wix_dir"
  exit 1
fi

regina_version=`grep 'regina_version = ' ./mkwxs.pl | sed -e "s/^.*= '//" -e "s/'.*\\$//"`
echo "Building installer for Regina $regina_version..."
echo

./mkwxs.pl

msi="Regina-$regina_version-$arch.msi"

"$wix_dir"/bin/candle -arch "$wix_arch" Regina.wxs WixUI_Regina.wxs
"$wix_dir"/bin/light -ext WixUIExtension -o "$msi" *.wixobj

echo
echo "SUCCESS: $msi"
exit 0

