#!/usr/bin/perl -w
use strict;

my %repos = ();

open(REPOS, "dnf repoquery --qf '%{NAME} %{VERSION}-%{RELEASE}'|") or die;
while (<REPOS>) {
    chomp;
    /^(\S+) (\S+)$/ or die $_;
    $repos{$1} = $2;
}
close(REPOS);

open(QUERY, "rpm -qa --qf '%{NAME} %{VERSION}-%{RELEASE}\n'|") or die;
while (<QUERY>) {
    chomp;
    /^(\S+) (\S+)$/ or die $_;
    if (defined $repos{$1}) {
        $repos{$1} eq $2 or print("$1 : installed $2, repositories have $repos{$1}\n");
    } else {
        print "$1 : installed but not in repositories\n";
    }
}
close(QUERY);
