#!/bin/bash
set -e

# version=7.0
# shasum=fa136c4d089c2b91030a9a836e9c104c0889fac3

version=7.1
shasum=845ef24861ff1679fa0b73241458057acd3ae174

src="regina-$version.tar.gz"
debsrc="regina-normal_$version.orig.tar.gz"

# releaseurl="https://github.com/regina-normal/regina/releases/download/regina-$version/$src"
releaseurl="http://www.maths.uq.edu.au/~bab/beta/$src"

if [ -e /usr/bin/curl ]; then
  /usr/bin/curl --location --output "$debsrc" "$releaseurl"
elif [ -e /usr/bin/wget ]; then
  /usr/bin/wget --output-document="$debsrc" "$releaseurl"
else
  echo "ERROR: curl/wget unavailable"
  exit 1
fi

if [ -e /usr/bin/shasum ]; then
  mysum=`/usr/bin/shasum "$debsrc" | cut -f1 -d' '`
elif [ -e /usr/bin/sha1sum ]; then
  mysum=`/usr/bin/sha1sum "$debsrc" | cut -f1 -d' '`
else
  echo "ERROR: shasum/sha1sum unavailable"
  exit 1
fi

if [ "$mysum" = "$shasum" ]; then
  echo "Downloaded $debsrc, shasums match"
else
  echo "ERROR: Incorrect shasum for $debsrc"
  exit 1
fi

exit 0
