#!/bin/bash
set -e

version=7.1
shasum=b20850467c041d9cf7ca4186720a373f0d48640e

src="regina-$version.tar.gz"

# releaseurl="https://github.com/regina-normal/regina/releases/download/regina-$version/$src"
releaseurl="http://www.maths.uq.edu.au/~bab/beta/$src"

if [ -e /usr/bin/curl ]; then
  /usr/bin/curl --location --output "$src" "$releaseurl"
elif [ -e /usr/bin/wget ]; then
  /usr/bin/wget --output-document="$src" "$releaseurl"
else
  echo "ERROR: curl/wget unavailable"
  exit 1
fi

if [ -e /usr/bin/shasum ]; then
  mysum=`/usr/bin/shasum "$src" | cut -f1 -d' '`
elif [ -e /usr/bin/sha1sum ]; then
  mysum=`/usr/bin/sha1sum "$src" | cut -f1 -d' '`
else
  echo "ERROR: shasum/sha1sum unavailable"
  exit 1
fi

if [ "$mysum" = "$shasum" ]; then
  echo "Downloaded $src, shasums match"
else
  echo "ERROR: Incorrect shasum for $src"
  exit 1
fi

exit 0
