FROM bab/DIST:SUITE

RUN apt-get update
RUN apt-get dist-upgrade -y
RUN apt-get install -y --no-install-recommends \
    ca-certificates debian-keyring vim
RUN apt-get clean

ADD apt-line-gen /etc/apt/apt-line-gen
RUN /etc/apt/apt-line-gen SUITE > /etc/apt/sources.list.d/regina.sources; \
    cat /etc/apt/sources.list.d/regina.sources; \
    rm /etc/apt/apt-line-gen
RUN apt-get update

RUN useradd -U -s /bin/bash -m user
