#!/bin/bash
#
# Usage: regina-gen-fedora <release>
#
set -e

release="$1"

if [ "$release" -lt 24 ]; then
  echo 'ERROR: For Fedora 24 and earlier, Regina used ad-hoc package downloads.'
  echo '       RPM repositories were not created.'
  exit 1
elif [ "$release" = 30 ]; then
  echo 'ERROR: Regina was not build for Fedora 30.'
  exit 1
fi

echo "Importing Regina's signing key..."
rpmkeys --import /etc/yum.repos.d/regina-key.asc

echo "Setting up repository for Fedora $release"

src=/etc/yum.repos.d/regina.repo
  cat > "$src" <<__END__
[regina]
name=Regina
baseurl=https://people.debian.org/~bab/rpm/regina/fedora/$release/
enabled=1
repo_gpgcheck=0
gpgcheck=1
gpgkey=https://people.debian.org/~bab/regina-key.txt
__END__

echo --------------------
cat "$src"
echo --------------------
