#!/bin/bash
#
# Note: on fink this requires librsvg2-bin.
#
set -e

for i in "$@"; do
  if [ -e "$i-dark.svg" ]; then
    options="$i $i-dark"
  else
    options="$i"
  fi

  for base in $options; do
    for j in 16 22 32; do
      size=$j
      if [ "$j" = 16 -a -e "$base-lores.svg" ]; then
        echo "16px: using lo-res SVG"
        rsvg-convert -w$size -h$size $base-lores.svg -o $base-$size.png
      else
        rsvg-convert -w$size -h$size $base.svg -o $base-$size.png
      fi
      size=$(($j + $j))
      rsvg-convert -w$size -h$size $base.svg -o $base-$j@2x.png
      size=$(($size + $j))
      rsvg-convert -w$size -h$size $base.svg -o $base-$j@3x.png
    done
  done
done

