#!/bin/bash
set -e

name="$1"
shift

test="python/testsuite/$name.test"
out="$AUTOPKGTEST_ARTIFACTS/python-$name.out"
filter="python/testsuite/$name.filter"

expect="python/testsuite/$name.out"
if [ ! -e "$expect" ]; then
	# This ubuntu release uses python >= 3.12.
	expect="python/testsuite/$name.out.v3"
fi

if [ -e "$filter" ]; then
	/usr/bin/regina-python "$test" "$@" | "$filter" > "$out"
else
	/usr/bin/regina-python "$test" "$@" > "$out"
fi
diff "$out" "$expect" 1>&2
exit $?
