#!/usr/bin/env bash
set -e

ver="$1"
if [ ! -e "/usr/share/debootstrap/scripts/$ver" ]; then
  echo "Unsupported Debian version: $ver"; exit 1
fi

myarch="`uname -m`"

arch="$2"
if [ -n "$arch" ]; then
  case "$arch" in
    i386) ;;
    amd64) echo "Cannot explicitly request architecture: $arch"; exit 1;;
    arm64) echo "Cannot explicitly request architecture: $arch"; exit 1;;
    *) echo "Unsupported Debian architecture: $arch"; exit 1;;
  esac
fi

if [ -n "$arch" ]; then
  tag="bab/debian:${ver}_${arch}"
else
  tag="bab/debian:$ver"
  arch=`dpkg --print-architecture`
fi

# Ancient debian versions live on the archive mirror, but debootstrap is not
# aware of this.  Here are the ones we care about for now...
archive=0
oldkey=0
case "$ver" in
  squeeze ) archive=1; oldkey=1 ;;
  wheezy ) archive=1; oldkey=1 ;;
  jessie ) archive=1; oldkey=1 ;;
  stretch ) archive=1 ;;
  * ) ;;
esac

if [ "$archive" = 0 ]; then
  echo "Preparing Debian $ver ($arch) as $tag ..."
  echo
  if [ "$oldkey" = 0 ]; then
    ./mkimage.sh -t "$tag" debootstrap --arch="$arch" "$ver"
  else
    ./mkimage.sh -t "$tag" debootstrap --arch="$arch" \
      --keyring=/usr/share/keyrings/debian-archive-removed-keys.gpg \
      "$ver"
  fi
else
  echo "Preparing Debian $ver ($arch, archived) as $tag ..."
  echo
  if [ "$oldkey" = 0 ]; then
    ./mkimage.sh -t "$tag" debootstrap --arch="$arch" "$ver" \
      http://archive.debian.org/debian
  else
    ./mkimage.sh -t "$tag" debootstrap --arch="$arch" \
      --keyring=/usr/share/keyrings/debian-archive-removed-keys.gpg \
      "$ver" http://archive.debian.org/debian
  fi
fi

exit 0
