#!/usr/bin/env bash
set -e

ver="$1"
if [ ! -e "/usr/share/debootstrap/scripts/$ver" ]; then
  echo "Unsupported Debian version: $ver"; exit 1
fi

myarch="`uname -m`"

arch="$2"
if [ -n "$arch" ]; then
  case "$arch" in
    i386) ;;
    amd64) echo "Cannot explicitly request architecture: $arch"; exit 1;;
    arm64) echo "Cannot explicitly request architecture: $arch"; exit 1;;
    *) echo "Unsupported Debian architecture: $arch"; exit 1;;
  esac
fi

if [ -n "$arch" ]; then
  tag="bab/debian:${ver}_${arch}"
else
  tag="bab/debian:$ver"
  arch=`dpkg --print-architecture`
fi

# Ancient debian versions live on the archive mirror, but debootstrap is not
# aware of this.  Here are the ones we care about for now...
archive=0
oldkey=0
case "$ver" in
  stretch ) archive=1 ;;
  * ) ;;
esac

debootstrap_opts="--arch=$arch"
debootstrap_args="$ver"

if [ "$archive" = 1 ]; then
  debootstrap_args="$debootstrap_args http://archive.debian.org/debian"
fi
if [ "$oldkey" = 1 ]; then
  debootstrap_opts="$debootstrap_opts --keyring=/usr/share/keyrings/debian-archive-removed-keys.gpg"
fi

echo "Preparing Debian $ver ($arch) as $tag ..."
echo
./mkimage.sh -t "$tag" debootstrap $debootstrap_opts $debootstrap_args

exit 0
