#!/usr/bin/env bash
set -e

ver="$1"
case "$ver" in
  [0-9][0-9]) ;;
  *) echo "Invalid Fedora version: $ver"; exit 1;;
esac

if [ -n "$2" ]; then
  echo "The fedora script does not support custom architectures."; exit 1
fi

tag=bab/fedora:$ver
distribution=fedora-$ver

myarch="`uname -m`"
case "$myarch" in
  x86_64) arch=amd64;;
  aarch64) arch=arm64;;
  *) echo "Unknown architecture: $myarch"; exit 1;;
esac

echo "Preparing Fedora $ver ($arch) as $tag ..."
echo

dir="$(mktemp -d ${TMPDIR:-/var/tmp}/docker-mkimage.XXXXXXXXXX)"
rootfsDir="$dir/rootfs"
tarFile="$dir/rootfs.tar.xz"

echo '----- Bootstrapping distribution -----'

mkdir -p "$rootfsDir"
rinse --directory "$rootfsDir" --arch "$arch" --distribution "$distribution"

if [ -d "$rootfsDir/etc/sysconfig" ]; then
	# allow networking init scripts inside the container to work without extra steps
	echo 'NETWORKING=yes' > "$rootfsDir/etc/sysconfig/network"
fi

echo '----- Creating /etc/resolv.conf -----'

# make sure /etc/resolv.conf has something useful in it
mkdir -p "$rootfsDir/etc"
rm -f "$rootfsDir/etc/resolv.conf"
cat > "$rootfsDir/etc/resolv.conf" <<'EOF'
nameserver 8.8.8.8
nameserver 8.8.4.4
EOF

echo '----- Updating distribution -----'

# We do not yet have dnf config-manager available.
sed -i -e 's/^enabled=1/enabled=0/' \
  "$rootfsDir"/etc/yum.repos.d/*update*.repo \
  "$rootfsDir"/etc/yum.repos.d/*cisco*.repo

chroot "$rootfsDir" dnf upgrade -y -b --refresh --setopt=install_weak_deps=False

chroot "$rootfsDir" dnf install -y -b --setopt=install_weak_deps=False \
  dnf-plugins-core
chroot "$rootfsDir" dnf config-manager --set-enabled fedora-source

# On Fedora 37, curl is broken which means rinse fails to install some helper
# packages.  The curl error seems to be this one:
# https://github.com/aarond10/https_dns_proxy/issues/136
# By this point in the installation, however, things should be working and so
# we can just install those missing packages now.
chroot "$rootfsDir" dnf install -y -b --setopt=install_weak_deps=False \
  vim-minimal dhclient

chroot "$rootfsDir" dnf clean all

echo
echo 'Enabled repositories:'
chroot "$rootfsDir" dnf repolist
echo

echo '----- Removing /dev and /proc -----'

# Docker mounts tmpfs at /dev and procfs at /proc so we can remove them
rm -rf "$rootfsDir/dev" "$rootfsDir/proc"
mkdir -p "$rootfsDir/dev" "$rootfsDir/proc"

if [ "$ver" -ge 36 ]; then
  echo '----- Initialising authselect -----'
  chroot "$rootfsDir" authselect select minimal --force
fi

echo '----- Creating Dockerfile -----'

cat > "$dir/Dockerfile" <<EOF
FROM scratch
ADD $(basename "$tarFile") /
CMD ["/bin/bash"]
RUN echo '%vendor Regina' >> /etc/rpm/macros
EOF

echo '----- Bundling filesystem -----'

tar -c -f "$tarFile" --numeric-owner --auto-compress -C "$rootfsDir" --transform='s,^./,,' .
rm -rf "$rootfsDir"

echo '----- Building docker image -----'

docker build -t "$tag" "$dir"
rm -rf "$dir"

echo '----- Done -----'

exit 0
