#!/usr/bin/env bash
set -e

ver="$1"
case "$ver" in
  15.[0-9]) ;;
  *) echo "Invalid openSUSE Leap version: $ver"; exit 1;;
esac

if [ -n "$2" ]; then
  echo "The opensuse script does not support custom architectures."; exit 1
fi

tag=bab/opensuse:$ver
distribution=opensuse-$ver

# Support history for architectures in openSUSE Leap 15.x:
# - x86_64:  supported for all versions
# - aarch64: in the main repo for >= 15.3;
#            in the ports repo for <= 15.2:
#            http://download.opensuse.org/ports/aarch64/distribution/leap/
# - i586:    not supported at all

myarch="`uname -m`"
case "$myarch" in
  x86_64) arch=amd64;;
  aarch64) arch=arm64;;
  *) echo "Unknown architecture: $myarch"; exit 1;;
esac

echo "Preparing openSUSE Leap $ver ($arch) as $tag ..."
echo

dir="$(mktemp -d ${TMPDIR:-/var/tmp}/docker-mkimage.XXXXXXXXXX)"
rootfsDir="$dir/rootfs"
tarFile="$dir/rootfs.tar.xz"

echo '----- Bootstrapping distribution -----'

mkdir -p "$rootfsDir"
rinse --directory "$rootfsDir" --arch "$arch" --distribution "$distribution"

echo '----- Updating distribution -----'

chroot "$rootfsDir" zypper refresh
chroot "$rootfsDir" zypper update -y
chroot "$rootfsDir" zypper clean

echo '----- Removing /dev and /proc -----'

# Docker mounts tmpfs at /dev and procfs at /proc so we can remove them
rm -rf "$rootfsDir/dev" "$rootfsDir/proc"
mkdir -p "$rootfsDir/dev" "$rootfsDir/proc"

echo '----- Creating Dockerfile -----'

cat > "$dir/Dockerfile" <<EOF
FROM scratch
ADD $(basename "$tarFile") /
CMD ["/bin/bash"]
RUN echo '%vendor Regina' >> /etc/rpm/macros
EOF

echo '----- Bundling filesystem -----'

tar -c -f "$tarFile" --numeric-owner --auto-compress -C "$rootfsDir" --transform='s,^./,,' .
rm -rf "$rootfsDir"

echo '----- Building docker image -----'

docker build -t "$tag" "$dir"
rm -rf "$dir"

echo '----- Done -----'

exit 0
