#!/usr/bin/env bash
set -e

ver="$1"
if [ ! -e "/usr/share/debootstrap/scripts/$ver" ]; then
  echo "Unsupported Ubuntu version: $ver"; exit 1
fi

myarch="`uname -m`"

arch="$2"
if [ -n "$arch" ]; then
  case "$arch" in
    i386) ;;
    amd64) echo "Cannot explicitly request architecture: $arch"; exit 1;;
    arm64) echo "Cannot explicitly request architecture: $arch"; exit 1;;
    *) echo "Unsupported Ubuntu architecture: $arch"; exit 1;;
  esac
fi

if [ -n "$arch" ]; then
  tag="bab/ubuntu:${ver}_${arch}"
else
  tag="bab/ubuntu:$ver"
  arch=`dpkg --print-architecture`
fi

# Some ubuntu versions live on the old-releases mirror, but debootstrap
# is not aware of this.  Here are the ones we care about for now...
archive=0
oldkey=0
case "$ver" in
  # LTS releases:
  lucid ) oldkey=1 ;;
  precise ) oldkey=1 ;;
  # Interim releases:
  groovy ) archive=1 ;;
  hirsute ) archive=1 ;;
  impish ) archive=1 ;;
  * ) ;;
esac

if [ "$archive" = 0 ]; then
  echo "Preparing Ubuntu $ver ($arch) as $tag ..."
  echo
  if [ "$oldkey" = 0 ]; then
    ./mkimage.sh -t "$tag" debootstrap --arch="$arch" "$ver"
  else
    ./mkimage.sh -t "$tag" debootstrap --arch="$arch" \
    --keyring=/usr/share/keyrings/ubuntu-archive-removed-keys.gpg \
    "$ver"
  fi
else
  echo "Preparing Ubuntu $ver ($arch, archived) as $tag ..."
  echo
  if [ "$oldkey" = 0 ]; then
    ./mkimage.sh -t "$tag" debootstrap --arch="$arch" "$ver" \
      http://old-releases.ubuntu.com/ubuntu
  else
    ./mkimage.sh -t "$tag" debootstrap --arch="$arch" \
      --keyring=/usr/share/keyrings/ubuntu-archive-removed-keys.gpg \
      "$ver" http://old-releases.ubuntu.com/ubuntu
  fi
fi

exit 0
