#!/bin/sh
#
# Usage: fix_rpm_version <regina_source_tree>
#
# Input: an RPM spec file.
#
# Output: the same RPM spec file, but with the Version: tag fixed to
# match what appears in the Regina source tree.
#
set -e

if [ ! -e "$1/CMakeLists.txt" ]; then
  echo "Usage: $0 <regina_source_tree>"
  exit 1
fi

if ! version_line="`grep -i '^set *(package_version [0-9.]\+)$' "$1/CMakeLists.txt"`"; then
  echo "ERROR: Could not locate Regina version in CMakeLists.txt"
  exit 1
fi

version="`echo "$version_line" | sed -e 's/^.* \([0-9.]\+\))/\1/'`"
sed -e "s/^Version: .*\$/Version: $version/"

