#!/bin/bash
set -e

if [ ! -d "$1/python/testsuite" ]; then
  echo "ERROR: Usage: $0 <regina_source_tree>"
  exit 1
fi

cd "$1/utils/testsuite"
for i in *.test; do
  name="${i/.test/}"
  echo "Test-Command: debian/tests/utils-test $name"
  echo "Features: test-name=utils-$name"
  echo
done

cd "../../python/testsuite"
for i in *.test; do
  name="${i/.test/}"
  if ( grep 'sys.argv.1' "$i" >/dev/null ); then
    echo "Test-Command: debian/tests/python-test $name python/testsuite"
  else
    echo "Test-Command: debian/tests/python-test $name"
  fi
  echo "Features: test-name=python-$name"
  echo
done

